name: Compile and Pack V8

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Fetch Tag
        run: echo "tag=`echo $GITHUB_REF | tr 'refs/tags/' ''`" >> $GITHUB_ENV

      - name: Install depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git $HOME/depot_tools
          export PATH=$HOME/depot_tools:$PATH
          echo "$HOME/depot_tools" >> $GITHUB_PATH
          gclient

      - name: Clone V8
        run: |
          fetch v8

      - name: Sync Dependencies
        run: |
          cd v8
          gclient sync --revision `echo ${{env.tag}} | tr -d v`

      - name: Make Output Directory
        run: mkdir out

      - name: Generate Build Files
        run: |
          cd v8
          gn gen ../out --args="`tr '\n' ' ' < ../gn_args`"

      - name: Compile V8
        run: |
          cd v8
          ninja -v -C ../out v8_monolith

      - name: Pack V8
        run: |
          mkdir -p package
          cp out/obj/libv8_monolith.a package/libv8.a
          cp -r v8/include package/include
          tar czf out/v8-${{env.tag}}-${{runner.os}}.tar.gz -C package .

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: v8-${{env.tag}}-${{runner.os}}
          path: package

      - name: Release V8
        uses: softprops/action-gh-release@v1
        with:
          files: out/v8-${{env.tag}}-${{runner.os}}.tar.gz
          body: Preconpiled V8
