name: Compile and Pack V8 (macOS and Linux)

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        arch: [x86_64, arm64]
        target: [desktop]
        include:
          - os: macos-latest
            arch: arm64
            target: ios
          - os: ubuntu-latest
            arch: arm64
            target: android

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Fetch Tag
        run: echo "tag=`echo $GITHUB_REF | tr -d 'refs/tags/'`" >> $GITHUB_ENV

      - name: Install depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git $HOME/depot_tools
          export PATH=$HOME/depot_tools:$PATH
          echo "$HOME/depot_tools" >> $GITHUB_PATH
          gclient

      - name: Clone V8
        run: |
          fetch v8

      - name: Sync Dependencies
        run: |
          cd v8
          gclient sync --revision `echo ${{env.tag}} | tr -d v`

      - name: Make Output Directory
        run: mkdir out

      - name: Install the Apple Certificate and Provisioning Profile
        if: ${{matrix.target == 'ios'}}
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Generate Build Files
        run: |
          cd v8
          if [ "${{matrix.arch}}" = "arm64" ]; then
            if [ "${{matrix.target}}" = "ios" ]; then
              gn gen ../out --args="`tr '\n' ' ' < ../gn_ios`"
            elif [ "${{matrix.target}}" = "android" ]; then
              gn gen ../out --args="`tr '\n' ' ' < ../gn_android`"
            else
              gn gen ../out --args="`tr '\n' ' ' < ../gn_args` target_cpu=\"arm64\" v8_target_cpu=\"arm64\""
            fi
          else
            gn gen ../out --args="`tr '\n' ' ' < ../gn_args`"
          fi

      - name: Sync Dependencies for arm64
        if: ${{matrix.arch == 'arm64'}}
        run: |
          cd v8
          gclient sync --revision `echo ${{env.tag}} | tr -d v`

      - name: Compile V8
        run: |
          cd v8
          ninja -v -C ../out v8_monolith

      - name: Pack V8
        run: |
          mkdir -p package
          cp out/obj/libv8_monolith.a package/libv8.a
          cp -r v8/include package/include
          tar czf out/v8-${{env.tag}}-${{runner.os}}-${{matrix.arch}}-${{matrix.target}}.tar.gz -C package .

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: v8-${{env.tag}}-${{runner.os}}-${{matrix.arch}}-${{matrix.target}}
          path: package

      - name: Release V8
        uses: softprops/action-gh-release@v1
        with:
          files: out/v8-${{env.tag}}-${{runner.os}}-${{matrix.arch}}-${{matrix.target}}.tar.gz
          body: Preconpiled V8
